# Generated by Django 4.1.3 on 2023-01-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='year',
            field=models.CharField(blank=True, max_length=8, verbose_name='生年月日'),
        ),
    ]
