# Generated by Django 4.1.3 on 2023-02-22 02:36

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_options_customuser_nick_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_screen_id',
            field=models.SlugField(default=accounts.models.create_id, max_length=30, verbose_name='ユーザーID'),
        ),
    ]
