# Generated by Django 4.1.3 on 2023-02-28 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_inquiry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inquiry',
            new_name='Post_Inquiry',
        ),
        migrations.AlterModelOptions(
            name='post_inquiry',
            options={'verbose_name': 'お問い合わせ一覧', 'verbose_name_plural': 'お問い合わせ一覧'},
        ),
    ]
