# Generated by Django 4.1.3 on 2023-02-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_rename_inquiry_post_inquiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_inquiry',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='対応済み'),
        ),
    ]
