# Generated by Django 4.1.3 on 2023-02-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_post_inquiry_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='Users_ProfileImages/', verbose_name='プロフィール画像'),
        ),
    ]
