# Generated by Django 4.1.3 on 2023-02-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='Users/default.jpg', upload_to='Users/ProfileImages', verbose_name='プロフィール画像'),
        ),
    ]
