# Generated by Django 4.1.3 on 2023-02-28 14:04

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='Users/default.jpg', null=True, upload_to=accounts.models._user_profile_avatar_upload_to, verbose_name='プロフィール画像'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='buildingname',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='建物名'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='職業'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nick_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ニックネーム'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tel',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='zipcode',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='郵便番号'),
        ),
    ]
