# Generated by Django 4.1.3 on 2023-03-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_customuser_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='read_terms',
            field=models.BooleanField(default=True, verbose_name='利用規約同意'),
            preserve_default=False,
        ),
    ]
