# Generated by Django 4.1.3 on 2023-03-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_customuser_read_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_inquiry',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='受付番号'),
        ),
    ]
