# Generated by Django 4.1.3 on 2023-03-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_post_inquiry_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_inquiry',
            name='number',
        ),
    ]
