# Generated by Django 4.1.3 on 2023-03-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_remove_post_inquiry_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_inquiry',
            name='read_field',
            field=models.BooleanField(default=False, verbose_name='送信確認'),
        ),
    ]
