# Generated by Django 4.1.3 on 2023-03-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_post_inquiry_read_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_inquiry',
            name='read_field',
            field=models.BooleanField(default=False, verbose_name='お問い合わせ送信確認'),
        ),
    ]
