# Generated by Django 4.1.3 on 2023-03-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_post_inquiry_read_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='year',
            field=models.DateTimeField(blank=True, default='2023-03-06', null=True, verbose_name='生年月日'),
        ),
    ]
