# Generated by Django 4.2.1 on 2023-12-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0033_alter_customuser_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="year",
            field=models.DateTimeField(
                blank=True, default="2023-12-07", null=True, verbose_name="生年月日"
            ),
        ),
    ]
