# Generated by Django 4.2.1 on 2023-12-07 13:44

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0035_certification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certification",
            options={"verbose_name": "資格情報", "verbose_name_plural": "資格情報"},
        ),
        migrations.AddField(
            model_name="certification",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=accounts.models.certificationImage,
                verbose_name="プロフィール画像",
            ),
        ),
    ]
