# Generated by Django 4.2.1 on 2023-12-07 13:59

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0036_alter_certification_options_certification_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certification",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=accounts.models.certificationImage,
                verbose_name="画像",
            ),
        ),
    ]
