# Generated by Django 4.2.1 on 2023-12-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0037_alter_certification_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="orderby",
            field=models.IntegerField(default=1, verbose_name="順番"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="year",
            field=models.DateTimeField(
                blank=True, default="2023-12-26", null=True, verbose_name="生年月日"
            ),
        ),
    ]
