# Generated by Django 4.2.1 on 2023-12-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0038_certification_orderby_alter_customuser_year"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="address",
            new_name="city",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="buildingname",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="zipcode",
        ),
        migrations.AddField(
            model_name="customuser",
            name="course",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="コース"
            ),
        ),
    ]
