# Generated by Django 4.2.1 on 2023-12-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0039_rename_address_customuser_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="PR文章"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="course",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="コース"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="year",
            field=models.DateTimeField(
                blank=True, default="2023-12-27", null=True, verbose_name="生年月日"
            ),
        ),
    ]
