# Generated by Django 4.2.1 on 2023-12-28 05:08

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0040_customuser_text_alter_customuser_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="banner",
            field=models.ImageField(
                blank=True,
                default="Users/default.jpg",
                null=True,
                upload_to=accounts.models._user_profile_avatar_upload_to,
                verbose_name="バナー画像",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="year",
            field=models.DateTimeField(
                blank=True, default="2023-12-28", null=True, verbose_name="生年月日"
            ),
        ),
    ]
