# Generated by Django 4.2.1 on 2023-12-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0041_customuser_banner_alter_customuser_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="call_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="呼び名"
            ),
        ),
    ]
