# Generated by Django 4.2.1 on 2023-12-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0042_customuser_call_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orderby", models.IntegerField(verbose_name="順番")),
                ("name", models.CharField(max_length=20, verbose_name="名前")),
                ("year", models.IntegerField(verbose_name="年数")),
            ],
            options={
                "verbose_name": "スキル一覧",
                "verbose_name_plural": "スキル一覧",
            },
        ),
    ]
