# Generated by Django 4.2.1 on 2023-12-29 05:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0043_skill"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orderby", models.IntegerField(verbose_name="順番")),
                ("name", models.CharField(max_length=20, verbose_name="名前")),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="取得日"
                    ),
                ),
            ],
            options={
                "verbose_name": "賞罰一覧",
                "verbose_name_plural": "賞罰一覧",
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="year",
            field=models.DateTimeField(
                blank=True, default="2023-12-29", null=True, verbose_name="生年月日"
            ),
        ),
    ]
